title: Elijah Oyekunle
email: elijah@elijahoyekunle.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer
baseurl: ""
url: "https://elijahoyekunle.com"
github_username:  eloyekunle
linkedin_username: elijahoyekunle
#header_pages:
#  - about.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - "*.ipynb"
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/

disqus:
  shortname: playmiceweb
